name: Rust cargo build & test

on:
  push:
    branches:
      - main
      - dev
    paths-ignore: "**.md"

  pull_request:
    branches:
      - main
      - dev
    paths-ignore: "**.md"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./DnsLiar

jobs:
  dnsliar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dnsliar
        run: cargo build -p dnsliar --verbose --features misp
      - name: Test dnsliar
        run: cargo test -p dnsliar --verbose --features misp

  redis-ctl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build redis-ctl
        run: cargo build -p redis-ctl --verbose
